# Generated by Django 4.1.5 on 2023-01-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('puntuacion_minima', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapaConceptual',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('MapaConceptual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.mapaconceptual')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('pregunta', models.CharField(max_length=50)),
                ('Evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.evaluacion')),
                ('Nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.nodo')),
            ],
        ),
    ]
