# Generated by Django 4.1.5 on 2023-01-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCat', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipoCat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idCont', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipoCont', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('idDoc', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipoDoc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('idMae', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipoMae', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('primerApellido', models.CharField(max_length=25)),
                ('segundoApellido', models.CharField(max_length=25)),
                ('sexo', models.CharField(max_length=10)),
                ('numNomina', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=20)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informatica.categoria')),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informatica.contrato')),
                ('Doctorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Informatica.doctorado')),
                ('Maestria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Informatica.maestria')),
            ],
        ),
    ]
